### ISSUE TITLE
Measured BW of the filter differs from the programmed settings.

### ISSUE THREAD

**Issue by nezumi-tech** [gcallipo/RadioDSP-Pico#2]
I assembled the circuit following the instructions and measured the characteristics of the filter with audio spectrum analyzer.
As a result, I found that the measured filter characteristics differed from the programmed settings.

![RasPi-Pico-BW](https://user-images.githubusercontent.com/25814413/212553319-2ec75239-6065-4afc-8ef1-54897664b002.jpg)

We can see that the attenuation of the filter (about -40dB) is correct and differs only in frequency.
Why are the filter frequencies different between settings and measurements?

**Comment by gcallipo** [comment]
Fine ! Thanks for the tests.

I think that the delay to performs the  calculatuon at the sample rate of 48 kHz Is the cause of the error, I think,  of you check the last filter, the cw the error Is less than the other.

Then a First test Is to decrease the taps Number of the am and ssb filters , but ... Better approach, It ti decimate more before filter.

Please could performs the same testa with the First version? The version that use the 8 bit in ADC? Because in that version I used more decimation in filtering session. 

Please take the same measure, to understood if using a decimation factor by 4 or more helps the filtering.

Another try Is to esclude the pre /post DNR filter , because when we concatenate two fir filters in cascade the results Is not overrides but It Will be changed.

Make this two experiments
1. Check the measurements with the First vetsion
2. Check the measurements with the second version, but excludes the DNR filter (the AVG) . 


I cannot make testa at the moment, mybe the next weekend.

Thanks.
G.
--
Inviato da Libero Mail

**Comment by nezumi-tech** [comment]
Thanks. I made additional experiments.

## Result of first version
I think the measurements are more closer to settings, but the difference remains.

![RasPi-Pico-BW_SF01](https://user-images.githubusercontent.com/25814413/212560593-589e5b52-4c85-4a52-bac3-de181fa00618.jpg)




## Result of second version without AVG filter
I think there is almost no difference compared to with AVG filter.

![RasPi-Pico-BW_SF02woAVG](https://user-images.githubusercontent.com/25814413/212560596-ce363141-bd71-430f-9e21-6f8630c1994f.jpg)

**Comment by gcallipo** [comment]
Ok thanks, It Is more clear.

In the First version I did some experiments to compensate a bit the filter, and you can see Better results.

The idea was to evaluate the filter using a base sample rate smaller than the original One. I can explain Better : evaluate the filter using a sample rate of 44 (or less) instead of 48 for am and ssb.  For the Cw use 10 (or less) kHz instead of 12 kHz , in this way we can compensate a bit the error in the eleboration chain. 

The challenge here Is to gain the Better results with this small processor, ofcorse using Cortex m4 of h7 It  Is simple,  but here we have a small Cortex m0 processor but I'm sure that we can obtains also acceptable results. The next steps Will be to move the output to I2S to decrease the PWM Noise. 

What program do you use to performs the spectral analisys ?

It Is interesting , normally I used the spectroid for android but It Is not extremaly efficient.

Thanks to interesting in the project.
Best 73 de Giuseppe.
--
Inviato da Libero Mail

**Comment by nezumi-tech** [comment]
Thanks.

I use WeveGane as the sweep signal generator. Use the sweep function (push "ﾊﾞｰ" button right side of frequency box) to 20Hz～24kHz sweep signal.
![image](https://user-images.githubusercontent.com/25814413/212599489-38ef3c83-d0b1-426a-8b74-457d51f1df96.png)

http://web.archive.org/web/20171102031127/http://efu.jp.net/soft/wg/wg.html

And WeveSpectra as the audio spectrum analyzer. Use the peak hold mode (activate "Peak" and "OVL1". red circle is reset) to get frequency response.
![image](https://user-images.githubusercontent.com/25814413/212599395-e5f34341-274f-400c-ba0e-f102177d8617.png)
http://web.archive.org/web/20171119095646/http://efu.jp.net/soft/ws/ws.html

Both software are only available in Japanese Language, but there is English 3rd-party help.
https://gtkc.net/wavespectra-wavegene-english-help

**Comment by nezumi-tech** [comment]
I tried overclocking the pico to 250MHz with earlephilhower/arduino-pico Arduino core.
https://github.com/earlephilhower/arduino-pico

Then, I achieved 0-4kHz filter BW with 0-6kHz AM/SSB filter mode, it was 0-2kHz BW before.
![image](https://user-images.githubusercontent.com/25814413/212699888-1c775658-5578-415f-bcde-2ec6f03348a5.png)

The overclocked frequency (250MHz) is 2 times higher than default (125 or 133MHz).
So I think that the sampling frequency is lowering due to the processing time.

I will make another pull request to migrate the Earlephilhower's Arduino core.

**Comment by gcallipo** [comment]
Yes that was the problem. 
Now and idea also could be to move the project to the original Pico SDK and try to compensate the sampling frequency with a small o different kind of filter. 

But your experimentation was really usefull. 

Thanks .
--
Inviato da Libero Mail

**Comment by gcallipo** [comment]
Please, check the filters now, I;ve updated the sample rate, from 48 to 24 khz and recalculate all filters, now the AM works at sample rate of 24 khz, the ssb works at sample rate of  12 khz (decimation by 2) and the CW works at sample rate of  6khz (decimation by 4 ), this is a starting point but I think that it works better.  
If possible check the bandwidt now. 

NOTE: I use the MBED updated at the new version 3.5.4.

**Comment by nezumi-tech** [comment]
I measured your updated Filter and we can see that AM Filter has 6kHz BW.

![image](https://user-images.githubusercontent.com/25814413/213868730-ffe8be70-8fcb-49a7-a381-9ac99ce4f632.png)


Also, SSB filter has 4 kHz BW.

![image](https://user-images.githubusercontent.com/25814413/213869037-744c7d8b-d6ac-4b1e-9d3c-2b05f27d052a.png)


And, CW filter has about 300 to 1,500 Hz BW.

![image](https://user-images.githubusercontent.com/25814413/213869128-8e994f13-adcc-4dc7-a520-ee9828590e58.png)

The frequency is quite similar, but it is seen that the performance of filter has degraded.  I think it is due to reduced number of taps.

**Comment by nezumi-tech** [comment]
I added the feature to measure the sample rate. please see new pull request.

![image](https://user-images.githubusercontent.com/25814413/213870603-f8d83572-ab99-4fac-a8ca-2ba6c651101f.png)

**Comment by gcallipo** [comment]
Ok, I can see that the BW Is like the specification of filter, and this Is good, and now we have a real limit of elaboration. 

The filter performance could be optimized , also, I think moving the output from PWM to I2S Digital output, I got a small max I2S amplifier and I Will try to change the output.

Also the filter could be optimized using more taps ofcorse.

Let's try with the overclocked processor.

Thanks for the test and support.
Ik8yfw.

Note:
For the I2S output I Will add a new project the SimpleFilter03 .
--
Inviato da Libero Mail

**Comment by gcallipo** [comment]
Close current sub project. 
Starting new experiments on SimpleAudioFilter06.
