### ISSUE TITLE
The 8k decimation may be causing high frequency noise in SSB and CW filter.

### ISSUE THREAD

**Issue by nezumi-tech** [gcallipo/RadioDSP-Pico#8]
The 8k decimation may be causing high frequency noise in SSB and CW filter. 

![image](https://user-images.githubusercontent.com/25814413/218421584-3668901a-4fb1-42da-b230-377b2e732043.png)
Figure 1 The frequency response in SSB filter mode.

I input the 10～4k Hz sweep sine wave to the filter and measure the frequency response. Then I found that there is high frequency noise in 5k to 8kHz. This noise is aliasing noise around 4k Hz nyquist frequency (sampling frequency 8kHz / 2).

I add post interpolation 0-4kHz filter with PR #7 .

**Comment by nezumi-tech** [comment]
High frequency noise around 5~8kHz is very painful to the ear. But, the noise around 16kHz is almost harmless because it is upper edge of human audible bandwidth.

**Comment by nezumi-tech** [comment]
Or, we can use fully 16kHz filters and don't use 8k decimation. 
https://github.com/nezumi-tech/RadioDSP-Pico/compare/Delete8kDecimation
But, this change will make it difficult to design of narrow bandwidth filters such as SSB and CW.

**Comment by gcallipo** [comment]
Yes correct this must be suppressed by the pre filter 8k because we done the decimation and It Is normal. Then we can adjust the actions of 8k LPF pre filter to eliminate that problem. 

The decimation process helps to decrease of some db the Noise level from the ADC Input Signal, but Need of tuning at the pre filtering. 

I think that we can recalculate the pre filter with more suppression.
--
Inviato da Libero Mail

**Comment by gcallipo** [comment]
Yes also a post interpolation can helps , but try to cut some frequencies using the pre interpolation also. 
This experimantation Is important because we Will use this filtering and decimation technic in the next project ( optimized sdr multimode Receiver )  with the Pico Pi. 

Thanks for the effort that you Place in the project.

Ik8yfw


--
Inviato da Libero Mail

**Comment by gcallipo** [comment]
No, we need the decimation, because the narrow filter works Better, and in the future project Will be the main process to works in multirate .

Then Better to use the decimator, we cannot delete It mybe recalculate It a bit narrow not 8k but cut at 5 but with a -60 db. 
--
Inviato da Libero Mail

**Comment by gcallipo** [comment]
No please don't cut the decimation we Need as base for the next project where working in multirate Is normal, in the next optimized sdr Receiver we Will use the multirate to process data as needs and to create good narrow filters with the small Pico . Then we need It. Mybe we can correct the 8k pre filter to cut before or add an interpolation post filtering.
--
Inviato da Libero Mail

**Comment by nezumi-tech** [comment]
I did not understand your objective, but I realized that you are creating this project for future Pi Pico SDR radio project.
Can I make the standalone lowcost audio DSP system for analog radios such as FT-818 with your (or my forked) code?
I think there are some differences in design concepts between a part of SDR radio and standalone system.

And I think post interpolation filter is needed to cutout image.
https://www.ni.com/docs/ja-JP/bundle/labview-digital-filter-design-toolkit-api-ref/page/lvdfdtconcepts/dfd_interpolation.html

**Comment by gcallipo** [comment]
Yes you are right, the primary objective Is to make the cheap and stand Alone filtering, i think that the decimation can help because allow to process more narrow filtering. Otherwhise you must avoid It but I think that Will be some problems on real near filtering.

The other side Is to reuse this experiences on next project, the Pico have not DSP hw estention and if we correct the decimation problema I think that Will be simple to make Better narrow filtering at 8k or less for CW . 

Then yes filter project, but if possible, to found the best results on cw and ssb narrow.


--
Inviato da Libero Mail

**Comment by gcallipo** [comment]
I think that missed the interpolation filter, I Will check for It as soon as possible, and I think that this can solve the uneanted signals problem.
--
Inviato da Libero Mail

**Comment by gcallipo** [comment]
Just as info, the interpolation filter will works at 8khz sample rate and must cut at 4khz or less. 

I will try Is as soon as possible.
--
Inviato da Libero Mail

**Comment by gcallipo** [comment]
> I did not understand your objective, but I realized that you are creating this project for future Pi Pico SDR radio project. Can I make the standalone lowcost audio DSP system for analog radios such as FT-818 with your (or my forked) code? I think there are some differences in design concepts between a part of SDR radio and standalone system.
> 
> And I think post interpolation filter is needed to cutout image. https://www.ni.com/docs/ja-JP/bundle/labview-digital-filter-design-toolkit-api-ref/page/lvdfdtconcepts/dfd_interpolation.html

Fine thenks, really I missed it !  I remmember that in other projects used the CMSIS Interpolator and decimator, and , ofcourse they performs all the works in background ... damn ! I missed it here .
Thenks for the check.

**Comment by gcallipo** [comment]
hello, I just added another SimpleAudioFilter08 project that uses a dynamic filter calculation algorithm according to the windowed sinc technique.  Listening is not bad, the filters are defined only by indicating the type ( low pass, High pass , passand or notch ), the Windows characteristic ( backman hemming etc ... ) and the sampling frequency.  This routine works in double to improve the calculation and then converts the coefficients to integers to allow faster processing.  The calculation of the coefficients is done in the second core in order not to alter the audio.  With a little tuning on the taps I think you can get good results.  I hope it can be useful to you.  Best 73 Ik8yfw Giuseppe
--
Inviato da Libero Mail

**Comment by nezumi-tech** [comment]
Awesome! I think standalone calculation of filter taps is useful to tune the filter in use.
